"""add chapter_number

Revision ID: 67a236e960de
Revises: 78950898416f
Create Date: 2026-10-02 12:55:58.879337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67a236e960de'
down_revision: Union[str, Sequence[str], None] = '78950898416f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapters', sa.Column('chapter_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chapters', 'chapter_number')
    # ### end Alembic commands ###
